<?php

namespace Techgym\PTFrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EjercicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EjercicioRepository extends EntityRepository
{
        public function findByRutinEje($id) {
        $query = $this->getEntityManager()->createQuery(
                        "SELECT n FROM TechgymPTFrontendBundle:Ejercicio n
                          JOIN n.rutin u
                          WHERE  u.id=:rutina_id")
                //->setParameter('alumno_id', 64);
                ->setParameters(array('rutina_id' => $id));

        return $query->getResult();
    }
     public function findByEjeRutin($id) {
        $query = $this->getEntityManager()->createQuery(
                        "SELECT n FROM TechgymPTFrontendBundle:Ejercicio n
                          JOIN n.rutin u
                          WHERE  u.id=:alumno_id")
                //->setParameter('alumno_id', 64);
                ->setParameters(array('alumno_id' => $id));

        return $query->getResult();
    }
}
