<?php

namespace Techgym\PTFrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PtUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PtUsuarioRepository extends EntityRepository
{
}
