<?php

namespace Techgym\PTFrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RutinaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RutinaRepository extends EntityRepository
{
     public function findByRutin($id) {
        $query = $this->getEntityManager()->createQuery(
                        "SELECT n FROM TechgymPTFrontendBundle:Rutina n
                          JOIN n.rutial u
                          WHERE  u.id=:alumno_id")
                //->setParameter('alumno_id', 64);
                ->setParameters(array('alumno_id' => $id));

        return $query->getResult();
    }
    

}
