<?php

namespace Techgym\PTFrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Rutina11Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Rutina11Repository extends EntityRepository
{
}
