imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
    imagenes_directorio: '%kernel.root_dir%/../web/bundles/techgymptfrontend/imagenes'
framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    translator:      { fallbacks: [en] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    #default_locale:  "%locale%"
    default_locale:  es
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        dql:
            datetime_functions:
                 convert_tz: DoctrineExtensions\Query\Mysql\ConvertTz
                 date: DoctrineExtensions\Query\Mysql\Date
                 date_format: DoctrineExtensions\Query\Mysql\DateFormat
                 dateadd: DoctrineExtensions\Query\Mysql\DateAdd
                 datesub: DoctrineExtensions\Query\Mysql\DateSub
                 datediff: DoctrineExtensions\Query\Mysql\DateDiff
                 day: DoctrineExtensions\Query\Mysql\Day
                 dayname: DoctrineExtensions\Query\Mysql\DayName
                 dayofweek: DoctrineExtensions\Query\Mysql\DayOfWeek
                 dayofyear: DoctrineExtensions\Query\Mysql\DayOfYear
                 div: DoctrineExtensions\Query\Mysql\Div
                 from_unixtime: DoctrineExtensions\Query\Mysql\FromUnixtime
                 hour: DoctrineExtensions\Query\Mysql\Hour
                 last_day: DoctrineExtensions\Query\Mysql\LastDay
                 minute: DoctrineExtensions\Query\Mysql\Minute
                 now: DoctrineExtensions\Query\Mysql\Now
                 month: DoctrineExtensions\Query\Mysql\Month
                 monthname: DoctrineExtensions\Query\Mysql\MonthName
                 second: DoctrineExtensions\Query\Mysql\Second
                 strtodate: DoctrineExtensions\Query\Mysql\StrToDate
                 time: DoctrineExtensions\Query\Mysql\Time
                 timediff: DoctrineExtensions\Query\Mysql\TimeDiff
                 timestampadd: DoctrineExtensions\Query\Mysql\TimestampAdd
                 timestampdiff: DoctrineExtensions\Query\Mysql\TimestampDiff
                 timetosec: DoctrineExtensions\Query\Mysql\TimeToSec
                 week: DoctrineExtensions\Query\Mysql\Week
                 weekday: DoctrineExtensions\Query\Mysql\WeekDay
                 year: DoctrineExtensions\Query\Mysql\Year
                 yearweek: DoctrineExtensions\Query\Mysql\YearWeek
                 unix_timestamp: DoctrineExtensions\Query\Mysql\UnixTimestamp

        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
