techgym_pt_frontend:
    resource: "@TechgymPTFrontendBundle/Resources/config/routing.yml"
    prefix:   /techgym
   
JAMNotasFrontendBundle:
  resource: "@JAMNotasFrontendBundle/Resources/config/routing.yml"
  prefix:   /notas

jazzyweb_aulas_mentor_alimentos:
    resource: "@JazzywebAulasMentorAlimentosBundle/Resources/config/routing.yml"
    prefix:   /alimentos

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login_check:
    pattern:   /login_check