# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
         Symfony\Component\Security\Core\User\User: plaintext
         Techgym\PTFrontendBundle\Entity\PtUsuario: md5
         Techgym\PTFrontendBundle\Entity\Alumno: md5
        

            
    role_hierarchy:
         ROLE_ADMIN:       ROLE_USER
         ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
         ROLE_PREMIUM: [ ROLE_REGISTRADO ]
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        base_datos:
             entity: { class: TechgymPTFrontendBundle:PtUsuario, property: username }
           

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        techgym_area_publica:
            pattern: ^/techgym/(activar|registro|login$)
            security: false
            anonymous:  ~
        
        techgym_area_protegida:
            pattern: ^/techgym/
            provider: base_datos
            form_login:
                login_path:  /techgym/login
                check_path:  /techgym/login_check
                #target_path_parameter: redirect_url
            logout:
                 path:   /techgym/logout
                 target: /techgym 
             
                 
        
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    
    access_control:
             - { path: ^/techgym/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
             - { path: ^/techgym/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
             - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }