# services:
#    techgym_pt_frontend.example:
#        class: Techgym\PTFrontendBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
parameters:
    techgym_pt_frontend.registro.class: Techgym\PTFrontendBundle\Services\Registro
    techgym_pt_frontend.update.class: Techgym\PTFrontendBundle\Services\Update
services:
    techgym_pt_frontend.registro:
        class: %techgym_pt_frontend.registro.class%
        arguments:
         - "@doctrine"
         - "@mailer"
         - "@templating"
         - "@security.encoder_factory"
    techgym_pt_frontend.update:
        class: %techgym_pt_frontend.update.class%
        arguments: 
          ['%imagenes_directorio%',"@doctrine","@mailer", "@templating","@security.encoder_factory"]
  
             
         
          
        